### ISSUE TITLE
Cannot compile in Ubuntu 18.04

### ISSUE THREAD

**Issue by i04n** [venediktov/CRUD#14]
I'm getting the following error:
/CRUD/service/mime_types.hpp:60:65: error: ‘constexpr const char* http::server::mime_types::extension_to_type(const char*)’ called in a constant expression
 constexpr const char* GIF  = mime_types::extension_to_type("gif");

**Comment by venediktov** [comment]
This is related to your compiler , it builds with C++14 . What version of gcc do you have ?

**Comment by i04n** [comment]
gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0

**Comment by venediktov** [comment]
Looks like gcc 7.3.0 bug 

the code builds by other versions here 
https://onlinegdb.com/ByoXcOYw4

if you can't upgrade your compiler for our project just pass -fpermissive to gcc 

https://github.com/venediktov/CRUD/blob/c5c90d176c5e5a6a71d007b2dea99de808122c20/service/CMakeLists.txt#L38

```
if (Boost_LIBRARIES)
    target_link_libraries( crud_service ${Boost_LIBRARIES} ${CMAKE_THREAD_LIBS_INIT})
    target_compile_options(crud_service PRIVATE -fpermissive)
endif()

```
 
to see what flags are passed 

```
make VERBOSE=1
```

**Comment by i04n** [comment]
I upgraded gcc and g++ to version 8 and it compiled ok. Thanks @venediktov !

**Comment by venediktov** [comment]
@i04n sounds good, thank you for testing and confirming !
